<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GameDir Condition="'$(GameDir)' == ''">D:\Program Files (x86)\Steam\steamapps\common\artofrally</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\src\AssetData.cs" Link="AssetData.cs" />
    <Reference Include="Newtonsoft.Json"><HintPath>$(GameDir)\artofrally_Data\Managed\Newtonsoft.Json.dll</HintPath><Private>true</Private></Reference>
  </ItemGroup>
</Project>
